Feature/11.2.x 12.1.x fixes
openfed/openfed pull request #59
Opened 2023-11-21 16:13 UTC by lramarojaona

2023-11-22 08:00 UTC, rutiolma requested changes

2023-11-22 08:00 UTC, rutiolma commented on scripts/composer/OpenfedUpdate.php
to review

2023-11-22 08:00 UTC, rutiolma commented on scripts/composer/OpenfedValidations.php
to review

2023-11-29 15:52 UTC, lramarojaona commented on CHANGELOG.md
> +06 September 2023 - Version 11.2.0
I've added the changelog for 12.1.0

2023-11-29 15:53 UTC, lramarojaona commented on composer.json
> +                "Issue #2858877: Allow for block visibility rules": "https://www.drupal.org/files/issues/2022-11-15/page_manager-block_visibility_conditions-2858877-71.patch"
I updated the patch with the last version

2023-11-29 15:53 UTC, lramarojaona commented on composer.json
> +        "drupal/twig_tweak": "2.10",
Fixed

2023-11-29 15:54 UTC, lramarojaona commented on openfed.info.yml
> +version: '11.2.0'
New version set to 12.1.0

2023-11-29 15:54 UTC, lramarojaona commented on openfed.install
> + * Fix a template regression issue with office_hours module.
This has been removed.

2023-11-30 08:07 UTC, rutiolma approved these changes

2023-11-30 14:12 UTC, merged